name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/gather-repo-stats:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/gather-repo-stats:latest
